/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cis4005.gui;

import com.sun.glass.events.KeyEvent;
import cis4005.connection.ModuleConnection;


/**
 *
 * @author jacob
 */
public class AddModule extends javax.swing.JFrame {
private Menu mainMenu;
    /**
     * Creates new form AddModule
     * @param mainMenu
     */
    public AddModule(Menu mainMenu) {
        initComponents();
        
        this.mainMenu=mainMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        moduleTitleIn = new javax.swing.JTextField();
        creditIn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        moduleCodeIn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        levelIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        semesterIn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addModule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 350));

        jLabel1.setText("ADD NEW MODULE");

        jLabel2.setText("Module title");

        moduleTitleIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleTitleInActionPerformed(evt);
            }
        });

        creditIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditInActionPerformed(evt);
            }
        });
        creditIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditInKeyTyped(evt);
            }
        });

        jLabel3.setText("Credits(int)");

        moduleCodeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleCodeInActionPerformed(evt);
            }
        });

        jLabel4.setText("ModuleCode");

        levelIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelInActionPerformed(evt);
            }
        });
        levelIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                levelInKeyTyped(evt);
            }
        });

        jLabel5.setText("Level( 4, 5, 6)");

        semesterIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterInActionPerformed(evt);
            }
        });
        semesterIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semesterInKeyTyped(evt);
            }
        });

        jLabel6.setText("Semester(1 or 2)");

        addModule.setText("ADD MODULE");
        addModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(moduleCodeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creditIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moduleTitleIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(levelIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(semesterIn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addModule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(moduleTitleIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(creditIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(moduleCodeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(levelIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addModule)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moduleTitleInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleTitleInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduleTitleInActionPerformed

    private void creditInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditInActionPerformed

    private void moduleCodeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleCodeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduleCodeInActionPerformed

    private void levelInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelInActionPerformed

    private void semesterInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterInActionPerformed

    private void addModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModuleActionPerformed
    String text1 = moduleTitleIn.getText();
    int text2 = Integer.parseInt(creditIn.getText());
    String text3 = moduleCodeIn.getText();
    int text4 = Integer.parseInt(levelIn.getText());
    int text5 = Integer.parseInt(semesterIn.getText());
    mainMenu.addModule(text1, text2, text3, text4, text5);
    
    }//GEN-LAST:event_addModuleActionPerformed

    private void creditInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditInKeyTyped
    char c = evt.getKeyChar();
    if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACKSPACE) ||  
            c == KeyEvent.VK_DELETE)
        {
        evt.consume();
        }
    }//GEN-LAST:event_creditInKeyTyped

    private void levelInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_levelInKeyTyped
    char c = evt.getKeyChar();
    if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACKSPACE) ||  
            c == KeyEvent.VK_DELETE)
    {
    evt.consume();
    }
    }//GEN-LAST:event_levelInKeyTyped

    private void semesterInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semesterInKeyTyped
    char c = evt.getKeyChar();
    if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACKSPACE) ||  
            c == KeyEvent.VK_DELETE)
    {
    evt.consume();
    }
    }//GEN-LAST:event_semesterInKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModule;
    private javax.swing.JTextField creditIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField levelIn;
    private javax.swing.JTextField moduleCodeIn;
    private javax.swing.JTextField moduleTitleIn;
    private javax.swing.JTextField semesterIn;
    // End of variables declaration//GEN-END:variables
}
